project_name: claude-history

before:
  hooks:
    - sh -c "cd src && go mod tidy"
    - sh -c "cd src && go test ./..."

builds:
  - main: .
    dir: ./src
    binary: claude-history
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - CLAUDE.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'typo'
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999

brews:
  - name: claude-history
    repository:
      owner: randlee
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/randlee/claude-history"
    description: "CLI tool for programmatic access to Claude Code's agent history storage"
    license: "MIT"
    directory: Formula
    install: |
      bin.install "claude-history"
    test: |
      system "#{bin}/claude-history", "--version"

release:
  github:
    owner: randlee
    name: claude-history
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
